### ISSUE TITLE
step definition files are syntax highlighted as ruby files 

### ISSUE THREAD

**Issue by cantonic** [drewda/cucumber-sublime-bundle#14]
When opening a step definition file the default syntax highlighting is Ruby. I manually have to chose Cucumber. Is that normal behavior or am I missing something?

**Comment by bubenkoff** [comment]
I believe yes, as it still has .rb extension, right?

**Comment by cantonic** [comment]
I don't know if it was an update, but now it works fine. When opening step definition files the syntax highlighting is set to "Cucumber Steps".
