### ISSUE TITLE
A setting to disable autocomplete would be nice

### ISSUE THREAD

**Issue by doryphores** [drewda/cucumber-sublime-bundle#17]
It would be nice to be able to disable the crawling of projects for step definitions.

Sublime crawls to a halt when loading large projects especially when said project includes a large bundle of gems.

**Comment by bubenkoff** [comment]
the problem why it halts should be fixed, please check
for that i believe you'd have to install this plugin from source to get the latest

**Comment by bubenkoff** [comment]
merged as well into st3 branch
 thanks!

**Comment by doryphores** [comment]
Thanks. I will give it a go.

**Comment by bubenkoff** [comment]
@doryphores still an issue for you?

**Comment by doryphores** [comment]
@bubenkoff Sorry for super late reply. Not an issue anymore as far as I can tell. Thanks!
