### ISSUE TITLE
remove st2 support?

### ISSUE THREAD

**Issue by bubenkoff** [drewda/cucumber-sublime-bundle#22]
ST3 is not 'new' anymore, so should we support st2 still (it's a bit annoying to do so)

**Comment by drewda** [comment]
Given that ST3 is still only available to registered users, I think it's worth continuing to offer an ST2 version. Of course, there is no need to keep feature parity between the two versions.

**Comment by bubenkoff** [comment]
right, i missed the fact that st3 is not 'free'
