### ISSUE TITLE
Merge Sublime3 to master

### ISSUE THREAD

**Issue by ejoubaud** [drewda/cucumber-sublime-bundle#23]
I think it would be safe to assume that now more people are using Sublime 3 than Sublime 2.

Some tools (Boxen at least) will pull Sublime plugins from Github repos (see the [Boxen module for Sublime](https://github.com/boxen/puppet-sublime_text)) but only from master (no way to specify a branch).

The Sublime 2 version could be kept on a branch for those who still use it.

**Comment by dkarter** [comment]
:+1:

**Comment by bubenkoff** [comment]
+1 for this
I created an issue like this already
The objection was that sb3 wasn't free

**Comment by bubenkoff** [comment]
@drewda what do you think?

**Comment by drewda** [comment]
We should retain ST2 support until ST3 is out of beta and available for demo/free usage.

( related to https://github.com/drewda/cucumber-sublime-bundle/issues/22 )
