### ISSUE TITLE
Unable to remove "&" table delimiter

### ISSUE THREAD

**Issue by morozgrafix** [drewda/cucumber-sublime-bundle#24]
This seems more like an issue with table cleaner plug-in by @amisarca 
I was attempting to remove `&` table delimiter in [Base File.sublime-settings (line 3)](https://github.com/drewda/cucumber-sublime-bundle/blob/st3/Base%20File.sublime-settings#L3) because I have  tables that include ampersand like example below and would only need to use `|` as a delimiter:

    | param1 | param2  |  
    | foo    | foo&bar |

I ended up putting changing `SEPARATOR = "&"` to `SEPARATOR = "|"` in [table_cleaner.py (line 17)](https://github.com/drewda/cucumber-sublime-bundle/blob/st3/table_cleaner.py#L17) to get around this limitation, but I was wondering if there is a more graceful solution to this.

**Comment by bubenkoff** [comment]
indeed, it makes more sense to have such:

```
"table_cleaner_delimiters": ["|", "\\\\"],
```

i don't think ampersand is a good separator

please make a PR

**Comment by drewda** [comment]
https://github.com/drewda/cucumber-sublime-bundle/pull/25
