### ISSUE TITLE
Auto-complete causes Sublime to hang if cursor is not in step

### ISSUE THREAD

**Issue by mrliptontea** [drewda/cucumber-sublime-bundle#26]
When I bring up auto-complete manually in any other line than the one defining a step, for example if I try to auto-complete a word in the feature name or feature description, Sublime Text hangs. I've tried to wait for few minutes to look if it ever finishes whatever it's doing, but it never does.

I'm not sure why is this happening, I've added `print('foo')` at the beginning of [on_query_completions](https://github.com/drewda/cucumber-sublime-bundle/blob/14e0f68763b47e51ddf841bddd44ecd63c9df1b5/GherkinAutoComplete.py#L114), opened the console but it was never reached.

I'm using Sublime Text 3, build 3083, Windows x64.

**Comment by mrliptontea** [comment]
The [while](https://github.com/drewda/cucumber-sublime-bundle/blob/14e0f68763b47e51ddf841bddd44ecd63c9df1b5/GherkinAutoComplete.py#L123) loop's condition is incorrect.

First of all, there should be `and`, not `or` because it should break if any of this is true. The `break` word at line 130 is not necessary.
Secondly, `sel.b` never reaches -1. So this will turn to infinite loop always if a current line does not contain the keywords given|when|then.

**Comment by drewda** [comment]
@mrliptontea thanks for reporting this error. Could you open a pull request with your proposed fix?

**Comment by mrliptontea** [comment]
I need to look into this, as I don't understand all the parts of this code.
To fix all the issues I've noticed here it might require a rewrite of quite a bit.

**Comment by danielkza** [comment]
I'm still seeing this, makes the plugin completely unusable. Any chance to merge that PR?

**Comment by maciejmyslinski** [comment]
It happends me too. OSX.

**Comment by drewda** [comment]
A belated "thank you" for your fix, @mrliptontea.
