### ISSUE TITLE
Few italian keywords are missing

### ISSUE THREAD

**Issue by robzenn92** [drewda/cucumber-sublime-bundle#41]
According to the [Gherkin's language](https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin-languages.json#L1674), the  italian's keywords for `Given` can be `Dato`,`Data`,`Dati`,`Date`. In this package, the only translation found for `Given` is `Dato` whereas the others are missing. So they should be added in `step_keyword` ([here](https://github.com/drewda/cucumber-sublime-bundle/blob/master/Cucumber%20Plain%20Text%20Feature.tmLanguage#L124)). Furthermore, the alias `Esempio` for `Scenario` is available in [Gherkin](https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin-languages.json#L1683) yet it is still missing [here](https://github.com/drewda/cucumber-sublime-bundle/blob/master/Cucumber%20Plain%20Text%20Feature.tmLanguage#L142). I'll open a pull request, hope you gonna merge soon.

Cheers.

**Comment by bubenkoff** [comment]
@robzenn92 np, thanks

**Comment by robzenn92** [comment]
Thanks a lot @bubenkoff !

**Comment by robzenn92** [comment]
Arg, now I see that you also have an st3 branch! Shall I create a PR also for that? Wondering about the next release.

@drewda @bubenkoff
